### ISSUE TITLE
macros take forever to load

### ISSUE THREAD

**Issue by nikscha** [Duet3D/PanelDueFirmware#56]
had to wait 10 seconds for the macros to load, kind of annoying...
also, macros on the main screen disappear if too many tools are defined

**Comment by wilriker** [comment]
Macros disappearing on the Control tab when a certain amount of tools is configured is intended because controlling tools is considered more important than quickly accessing macros that can be reached via an extra popup also.

In PanelDueFirmware 3.2 initial loading of macros won't be quicker but at least you get a state "Initializing".

I'll close this one because loading the macros should not take priority over initializing the panel.

Please feel free to reopen if you can provide a reason why to consider changing this behavior.
